// Timeline question pack. The game engine intentionally owns all mechanics;
// this file is content only and can be swapped through QUESTION_WORKFLOW.md.
window.TIMELINE_JEOPARDY_PACK = {
  id: "timeline-general-knowledge-v3",
  name: "General Knowledge",
  title: "WHAT HAPPENED FIRST?",
  subtitle: "Pick the earlier event.",
  genre: "Timeline",
  categories: [
    { name: "Technology", clues: [
      { id:"timeline-v3-technology-100", q:"Which happened first: the first website went online, or the first SMS text message was sent?", h:"Both milestones arrived in the early 1990s, about a year apart.", a:"the first website went online first", choices:["the first website went online","the first SMS text message was sent"] },
      { id:"timeline-v3-technology-200", q:"Which happened first: the original PlayStation launched in Japan, or the DVD format was announced?", h:"Both appeared in the mid-1990s as home entertainment was rapidly changing.", a:"the original PlayStation launched in Japan first", choices:["the original PlayStation launched in Japan","the DVD format was announced"] },
      { id:"timeline-v3-technology-300", q:"Which happened first: Windows 95 was released, or Java 1.0 was released?", h:"These landmark software releases arrived less than a year apart.", a:"Windows 95 was released first", choices:["Windows 95 was released","Java 1.0 was released"] },
      { id:"timeline-v3-technology-400", q:"Which happened first: Google Maps launched, or the first video was uploaded to YouTube?", h:"Both happened in 2005, during the first half of the year.", a:"Google Maps launched first", choices:["Google Maps launched","the first video was uploaded to YouTube"] },
      { id:"timeline-v3-technology-500", q:"Which happened first: SpaceX's Falcon 1 reached orbit, or Bitcoin's genesis block was created?", h:"These milestones arrived on opposite sides of New Year's Day, only a few months apart.", a:"SpaceX's Falcon 1 reached orbit first", choices:["SpaceX's Falcon 1 reached orbit","Bitcoin's genesis block was created"], special:true, followupId:"timeline-v3-technology-500-followup", fq:"In what year did Falcon 1 first reach orbit?", fa:"2008 — Falcon 1 reached orbit in September 2008.", fchoices:["2006","2007","2008","2009"], fcorrect:"2008" }
    ]},
    { name: "History", clues: [
      { id:"timeline-v3-history-100", q:"Which happened first: the Gutenberg Bible was completed, or Columbus reached the Caribbean?", h:"These landmarks were separated by several decades in the 1400s.", a:"the Gutenberg Bible was completed first", choices:["the Gutenberg Bible was completed","Columbus reached the Caribbean"] },
      { id:"timeline-v3-history-200", q:"Which happened first: the Battle of Waterloo, or the Monroe Doctrine was announced?", h:"Both occurred in the early 19th century, eight years apart.", a:"the Battle of Waterloo first", choices:["the Battle of Waterloo","the Monroe Doctrine was announced"] },
      { id:"timeline-v3-history-300", q:"Which happened first: California became a U.S. state, or the Crimean War began?", h:"Both events occurred during the first half of the 1850s.", a:"California became a U.S. state first", choices:["California became a U.S. state","the Crimean War began"] },
      { id:"timeline-telegraph-suez-400", q:"Which happened first: the first transatlantic telegraph cable was completed, or the Suez Canal opened?", h:"Both projects reshaped global communication and trade during the 1860s.", a:"the first transatlantic telegraph cable was completed first", choices:["the first transatlantic telegraph cable was completed","the Suez Canal opened"] },
      { id:"timeline-v3-history-500", q:"Which happened first: the Panama Canal opened, or the League of Nations held its first meeting?", h:"These milestones were separated by about six years in the early 20th century.", a:"the Panama Canal opened first", choices:["the Panama Canal opened","the League of Nations held its first meeting"], special:true, followupId:"timeline-v3-history-500-followup", fq:"In what year did the Panama Canal open?", fa:"1914 — the Panama Canal opened in August 1914.", fchoices:["1908","1911","1914","1917"], fcorrect:"1914" }
    ]},
    { name: "Pop Culture", clues: [
      { id:"timeline-v3-pop-culture-100", q:"Which happened first: the original Star Wars opened in theaters, or Grease opened in theaters?", h:"These blockbusters arrived in consecutive summers during the late 1970s.", a:"the original Star Wars opened in theaters first", choices:["the original Star Wars opened in theaters","Grease opened in theaters"] },
      { id:"timeline-v3-pop-culture-200", q:"Which happened first: Sony released the Walkman, or Pac-Man debuted in arcades?", h:"These Japanese pop-culture icons arrived less than a year apart.", a:"Sony released the Walkman first", choices:["Sony released the Walkman","Pac-Man debuted in arcades"] },
      { id:"timeline-v3-pop-culture-300", q:"Which happened first: Nintendo released the Game Boy, or The Fresh Prince of Bel-Air premiered?", h:"One arrived in 1989 and the other in 1990.", a:"Nintendo released the Game Boy first", choices:["Nintendo released the Game Boy","The Fresh Prince of Bel-Air premiered"] },
      { id:"timeline-v3-pop-culture-400", q:"Which happened first: Toy Story was released, or the Spice Girls released Wannabe?", h:"These 1990s hits arrived in consecutive years.", a:"Toy Story was released first", choices:["Toy Story was released","the Spice Girls released Wannabe"] },
      { id:"timeline-v3-pop-culture-500", q:"Which happened first: Spotify launched to the public, or Avatar opened in theaters?", h:"These entertainment milestones arrived near the end of the 2000s.", a:"Spotify launched to the public first", choices:["Spotify launched to the public","Avatar opened in theaters"], special:true, followupId:"timeline-v3-pop-culture-500-followup", fq:"In which country was Spotify founded?", fa:"Sweden — Spotify was founded in Stockholm.", fchoices:["Denmark","Finland","Norway","Sweden"], fcorrect:"Sweden" }
    ]},
    { name: "Science", clues: [
      { id:"timeline-v3-science-100", q:"Which happened first: Mendeleev presented his periodic table, or Bell received his telephone patent?", h:"Both breakthroughs came during the second half of the 19th century.", a:"Mendeleev presented his periodic table first", choices:["Mendeleev presented his periodic table","Bell received his telephone patent"] },
      { id:"timeline-v3-science-200", q:"Which happened first: X-rays were discovered, or aspirin was registered as a trademark?", h:"These medical milestones happened only a few years apart in the 1890s.", a:"X-rays were discovered first", choices:["X-rays were discovered","aspirin was registered as a trademark"] },
      { id:"timeline-v3-science-300", q:"Which happened first: insulin was first used to treat a patient, or Tutankhamun's tomb was discovered?", h:"Both events made headlines in 1922, months apart.", a:"insulin was first used to treat a patient first", choices:["insulin was first used to treat a patient","Tutankhamun's tomb was discovered"] },
      { id:"timeline-v3-science-400", q:"Which happened first: Sputnik 1 was launched, or the first working laser was demonstrated?", h:"These advances opened new technological eras near the end of the 1950s.", a:"Sputnik 1 was launched first", choices:["Sputnik 1 was launched","the first working laser was demonstrated"] },
      { id:"timeline-v3-science-500", q:"Which happened first: the Human Genome Project was declared complete, or the Curiosity rover landed on Mars?", h:"These major science milestones were separated by nearly a decade.", a:"the Human Genome Project was declared complete first", choices:["the Human Genome Project was declared complete","the Curiosity rover landed on Mars"], special:true, followupId:"timeline-v3-science-500-followup", fq:"In what year was the Human Genome Project declared complete?", fa:"2003 — completion was announced in April 2003.", fchoices:["1999","2001","2003","2005"], fcorrect:"2003" }
    ]},
    { name: "Sports", clues: [
      { id:"timeline-v3-sports-100", q:"Which happened first: the first Kentucky Derby was run, or the first Boston Marathon was held?", h:"Both annual American races began in the late 19th century.", a:"the first Kentucky Derby was run first", choices:["the first Kentucky Derby was run","the first Boston Marathon was held"] },
      { id:"timeline-v3-sports-200", q:"Which happened first: the first Tour de France, or the first Indianapolis 500?", h:"These famous races began eight years apart in the early 1900s.", a:"the first Tour de France first", choices:["the first Tour de France","the first Indianapolis 500"] },
      { id:"timeline-v3-sports-300", q:"Which happened first: the first Winter Olympic Games, or the first FIFA World Cup?", h:"Both international competitions began during the 1920s and 1930s.", a:"the first Winter Olympic Games first", choices:["the first Winter Olympic Games","the first FIFA World Cup"] },
      { id:"timeline-v3-sports-400", q:"Which happened first: Roger Bannister ran a mile in under four minutes, or Super Bowl I was played?", h:"These sporting landmarks were separated by more than a decade.", a:"Roger Bannister ran a mile in under four minutes first", choices:["Roger Bannister ran a mile in under four minutes","Super Bowl I was played"] },
      { id:"timeline-v3-sports-500", q:"Which happened first: the first X Games, or the WNBA's inaugural season?", h:"Both debuted during the middle of the 1990s.", a:"the first X Games first", choices:["the first X Games","the WNBA's inaugural season"], special:true, followupId:"timeline-v3-sports-500-followup", fq:"In what year were the first X Games held?", fa:"1995 — the inaugural Extreme Games were held in 1995.", fchoices:["1993","1994","1995","1996"], fcorrect:"1995" }
    ]}
  ]
};
window.TIMELINE_QUESTION_PACKS=window.TIMELINE_QUESTION_PACKS||{};
window.TIMELINE_QUESTION_PACKS[window.TIMELINE_JEOPARDY_PACK.id]=window.TIMELINE_JEOPARDY_PACK;
